carteleria_carteleria:
    resource: "@AppBundle/Resources/config/routing.yml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
