security:
    encoders:
        AppBundle\Entity\Usuario: { algorithm: sha512, iterations: 5 }

        Symfony\Component\Security\Core\User\User: plaintext
#        Symfony\Component\Security\Core\User\User: { algorithm: sha512, iterations: 5 }

    role_hierarchy:
        ROLE_ADMINISTRADOR:    ROLE_ADMINISTRADOR
        ROLE_USUARIO: ROLE_USUARIO
        ROLE_SUPER_ADMIN: [ROLE_ADMINISTRADOR, ROLE_ALLOWED_TO_SWITCH]

    providers:
        unidos:
            chain:
                providers: [in_memory, base_datos]
        in_memory:
            memory:
                users:
                    administrador:  { password: a!!!x, roles: [ 'ROLE_ADMINISTRADOR' ] }
                    admin: { password: a!!!!x, roles: [ 'ROLE_SUPER_ADMIN' ] }
        base_datos:
                entity: { class: AppBundle\Entity\Usuario, property: nombre }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
