estudiotipoget:
    path:     /estudiotipo/getall
    defaults: { _controller: AppBundle:Nomencladores:estudiotipoget }

estudioestadosget:
    path:     /estudioestado/getall
    defaults: { _controller: AppBundle:Nomencladores:estudioestadoget }

estudiotitulos:
    path:     /estudiotitulos/getall
    defaults: { _controller: AppBundle:Nomencladores:estudiotituloget }

annos:
    path:     /annos/getall
    defaults: { _controller: AppBundle:Nomencladores:annosget }

idiomas:
    path:     /idiomas/getall
    defaults: { _controller: AppBundle:Nomencladores:idiomasget }

niveles:
    path:     /niveles/getall
    defaults: { _controller: AppBundle:Nomencladores:nivelesget }

habilidad:
    path:     /habilidades/getall
    defaults: { _controller: AppBundle:Nomencladores:habilidadesget }

postulacionespre:
    path:     /postulacionespre/getall
    defaults: { _controller: AppBundle:Nomencladores:postulacionespreget }

actividadempresa:
    path:     /actividadempresa/getall
    defaults: { _controller: AppBundle:Nomencladores:actividadempresaget }