login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }
    methods: POST

checktoken:
    path:     /checktoken
    defaults: { _controller: AppBundle:Security:checkToken }
    methods: POST

checktokenAdmin:
    path:     /checktokenAdmin
    defaults: { _controller: AppBundle:Security:checktokenAdmin }
    methods: POST
