<?php

namespace AppBundle\Entity;

/**
 * AnnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnoRepository extends \Doctrine\ORM\EntityRepository
{
}
