<?php

namespace AppBundle\Entity;

/**
 * CurriculumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurriculumRepository extends \Doctrine\ORM\EntityRepository
{
}
