<?php

namespace AppBundle\Entity;

/**
 * EstudioIdiomaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudioIdiomaRepository extends \Doctrine\ORM\EntityRepository
{
}
