<?php

namespace AppBundle\Entity;

/**
 * EstudioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudioRepository extends \Doctrine\ORM\EntityRepository
{
}
