<?php

namespace AppBundle\Entity;

/**
 * EstudioTituloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudioTituloRepository extends \Doctrine\ORM\EntityRepository
{
}
