<?php

namespace AppBundle\Entity;

/**
 * EstudiotipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudiotipoRepository extends \Doctrine\ORM\EntityRepository
{
}
