<?php

namespace AppBundle\Entity;

/**
 * EstudioestadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudioestadoRepository extends \Doctrine\ORM\EntityRepository
{
}
