<?php

namespace AppBundle\Entity;

/**
 * ExperienciaLaboralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienciaLaboralRepository extends \Doctrine\ORM\EntityRepository
{
}
