<?php

namespace AppBundle\Entity;

/**
 * HabilidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HabilidadRepository extends \Doctrine\ORM\EntityRepository
{
}
