<?php

namespace AppBundle\Entity;

/**
 * HijosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HijosRepository extends \Doctrine\ORM\EntityRepository
{
}
