<?php

namespace AppBundle\Entity;

/**
 * LocalidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalidadRepository extends \Doctrine\ORM\EntityRepository
{
}
