<?php

namespace AppBundle\Entity;

/**
 * NivelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NivelRepository extends \Doctrine\ORM\EntityRepository
{
}
