<?php

namespace AppBundle\Entity;

/**
 * ofertalaboralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ofertalaboralRepository extends \Doctrine\ORM\EntityRepository
{
}
