<?php

namespace AppBundle\Entity;

/**
 * TipotelefonoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipotelefonoRepository extends \Doctrine\ORM\EntityRepository
{
}
