<?php

namespace AppBundle\Entity;

/**
 * TipodocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipodocRepository extends \Doctrine\ORM\EntityRepository
{
}
